In [1]:
from datascience import *
import numpy as np

In [2]:
# Functions

In [3]:
def double(x):
    return 2 * x

In [4]:
double(3)

6

In [5]:
double(-4)

-8

In [6]:
y = 5
double(y/4)

2.5

In [7]:
double(y)

10

In [8]:
z = double(y)
z

10

In [9]:
counts = make_array(1, 2, 3)
total = sum(counts)
np.round((counts/total) * 100, 2)

array([16.67, 33.33, 50.  ])

In [10]:
def percent(s):
    """Convert the counts to percents out of the total."""
    total = sum(s)
    return np.round((s/total) * 100, 2)

percent(counts)

array([16.67, 33.33, 50.  ])

In [11]:
percent(make_array(1, 1, 1, 1))

array([25., 25., 25., 25.])

In [12]:
def percents(counts, decimal_places=2):
    """Convert the counts to percents out of the total."""
    total = sum(counts)
    return np.round((counts/total)*100, decimal_places)

parts = make_array(2, 1, 4)
"Rounded to 1 decimal place:", percents(parts, 1), "or", percents(parts, decimal_places=1)

('Rounded to 1 decimal place:',
 array([28.6, 14.3, 57.1]),
 'or',
 array([28.6, 14.3, 57.1]))

In [13]:
"Rounded to the default number of decimal places:", percents(parts)

('Rounded to the default number of decimal places:',
 array([28.57, 14.29, 57.14]))

In [14]:
help(percents)

Help on function percents in module __main__:

percents(counts, decimal_places=2)
    Convert the counts to percents out of the total.



In [15]:
# Show you the arguments and docstring's function

def cut_off_at_100(x):
    """The smaller of x and 100"""
    return min(x, 100)

cut_off_at_100(17)

17

In [16]:
cut_off_at_100(117)

100

In [17]:
ages = Table().with_columns(
    'Person', make_array('A', 'B', 'C', 'D', 'E', 'F'),
    'Age', make_array(17, 117, 52, 100, 6, 101)
)
ages.apply(cut_off_at_100, 'Age')

array([ 17, 100,  52, 100,   6, 100])

In [18]:
ages.with_column(
    'Cut Off Age', ages.apply(cut_off_at_100, 'Age')
)

Person | Age  | Cut Off Age
A      | 17   | 17
B      | 117  | 100
C      | 52   | 52
D      | 100  | 100
E      | 6    | 6
F      | 101  | 100

In [20]:
# Define a new name for the function 'cut_off_at_100'
cut_off = cut_off_at_100