In [2]:
from datascience import *
import numpy as np
import math as m
import IPython.display

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

<br><br><br><br><br><br><br><br><br><br><br><br>

# Numpy

## arange

In [3]:
# Make an array with numbers from 0 up to 3
np.arange(0, 4)

array([0, 1, 2, 3])

In [4]:
# Create an array with the multiples of 99 from 0 up to 9999.
multiples_of_99 = np.arange(0, 9999+99, 99)
multiples_of_99

array([   0,   99,  198,  297,  396,  495,  594,  693,  792,  891,  990,
       1089, 1188, 1287, 1386, 1485, 1584, 1683, 1782, 1881, 1980, 2079,
       2178, 2277, 2376, 2475, 2574, 2673, 2772, 2871, 2970, 3069, 3168,
       3267, 3366, 3465, 3564, 3663, 3762, 3861, 3960, 4059, 4158, 4257,
       4356, 4455, 4554, 4653, 4752, 4851, 4950, 5049, 5148, 5247, 5346,
       5445, 5544, 5643, 5742, 5841, 5940, 6039, 6138, 6237, 6336, 6435,
       6534, 6633, 6732, 6831, 6930, 7029, 7128, 7227, 7326, 7425, 7524,
       7623, 7722, 7821, 7920, 8019, 8118, 8217, 8316, 8415, 8514, 8613,
       8712, 8811, 8910, 9009, 9108, 9207, 9306, 9405, 9504, 9603, 9702,
       9801, 9900, 9999])

## average

In [5]:
np.average(multiples_of_99)

4999.5

## round

In [6]:
counts = make_array(1, 2, 3)
total = sum(counts)
np.round((counts/total) * 100, 2)

array([16.67, 33.33, 50.  ])

## random.choice

In [7]:
two_groups = make_array('treatment', 'control')
np.random.choice(two_groups)

'control'

## count_nonzero

In [8]:
tosses = make_array('Tails', 'Heads', 'Tails', 'Heads', 'Heads')
np.count_nonzero(tosses == 'Heads')

3

## append

In [9]:
np.append(make_array(1, 2, 3), 4)

array([1, 2, 3, 4])

In [10]:
np.append(make_array(1, 2, 3), 'four')

array(['1', '2', '3', 'four'], dtype='<U21')

In [11]:
np.append(make_array(1, 2, 3), make_array(4, 5, 6))

array([1, 2, 3, 4, 5, 6])

In [12]:
## 